# Generated by Django 5.1.4 on 2025-03-30 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_customer_collection_day_of_month_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='delivery_date',
            field=models.DateField(blank=True, help_text='Date when the order should be delivered (optional)', null=True),
        ),
    ]
