# Generated by Django 5.1.4 on 2025-03-30 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_bank_payment_bank'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bank',
            name='account_number',
        ),
        migrations.RemoveField(
            model_name='bank',
            name='branch',
        ),
        migrations.RemoveField(
            model_name='bank',
            name='ifsc_code',
        ),
        migrations.AlterField(
            model_name='bank',
            name='is_default',
            field=models.BooleanField(default=False, help_text='Set as the default payment method'),
        ),
        migrations.AlterField(
            model_name='bank',
            name='name',
            field=models.CharField(help_text="Payment receiving account (e.g., 'Main Account', 'Cash')", max_length=100),
        ),
    ]
