# Generated by Django 5.1.4 on 2025-03-30 11:52

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_remove_bank_account_number_remove_bank_branch_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='collection_day_of_month',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='collection_day_of_week',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='collection_frequency',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='customer_type',
        ),
        migrations.AddField(
            model_name='order',
            name='collection_day_of_month',
            field=models.IntegerField(blank=True, help_text='Day of the month for monthly collections (1-31)', null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(31)]),
        ),
        migrations.AddField(
            model_name='order',
            name='collection_day_of_week',
            field=models.IntegerField(blank=True, choices=[(0, 'Monday'), (1, 'Tuesday'), (2, 'Wednesday'), (3, 'Thursday'), (4, 'Friday'), (5, 'Saturday'), (6, 'Sunday')], help_text='Day of the week for weekly collections', null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='collection_frequency',
            field=models.CharField(choices=[('NONE', 'No Regular Collection'), ('WEEKLY', 'Weekly'), ('MONTHLY', 'Monthly')], default='NONE', max_length=10),
        ),
        migrations.AddField(
            model_name='order',
            name='next_payment_date',
            field=models.DateField(blank=True, help_text='Calculated next payment date based on collection frequency', null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='order_type',
            field=models.CharField(choices=[('B2C_READY_CASH', 'B2C Ready Cash'), ('B2C_EMI', 'B2C EMI'), ('B2B', 'B2B')], default='B2C_READY_CASH', max_length=20),
        ),
    ]
