# Generated by Django 5.1.4 on 2025-03-30 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_remove_customer_collection_day_of_month_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='emi_amount',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Amount to be collected per installment for EMI orders', max_digits=10, null=True),
        ),
    ]
