# Generated by Django 5.1.4 on 2025-03-30 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_order_emi_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_type',
            field=models.CharField(choices=[('B2C_READY_CASH', 'B2C Ready Cash'), ('B2C_EMI', 'B2C EMI'), ('B2B_READY_CASH', 'B2B Ready Cash'), ('B2B_EMI', 'B2B EMI')], default='B2C_READY_CASH', max_length=20),
        ),
    ]
