# Generated by Django 5.1.4 on 2025-03-31 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_orderpayment_payment_orders'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderpayment',
            name='paid_amount',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Amount already paid for this installment', max_digits=10),
        ),
    ]
