# Generated by Django 5.1.4 on 2025-03-31 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_orderpayment_paid_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderpayment',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('partial', 'Partially Paid'), ('paid', 'Paid')], default='pending', help_text='Current payment status for this installment', max_length=20),
        ),
    ]
